# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash make

variables:
  LC_ALL: 'C.UTF-8'
  LANG: 'C.UTF-8'
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build x64:
  stage: build
  tags:
    - docker
  script:
    - make docker

Publish x64:
  stage: deploy
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - make docker-publish
  when: on_success
  only:
    - master

# Will probably timeout on gitlab
# Publish Multiarch:
#   stage: deploy
#   script:
#     - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
#     - make docker-multiarch-publish
#   only:
#     - master
