# UBCUAS Gitlab-CI configuration

image: itseris/buildx:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache bash make

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build Multiarch:
  stage: build
  tags:
    - docker
  script:
    - make docker-multiarch

Publish Multiarch:
  stage: deploy
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - make docker-multiarch-publish
  when: on_success
  only:
    - master
