# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uuaspb.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uuaspb.proto',
  package='uuaspb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cuuaspb.proto\x12\x06uuaspb\"G\n\rGeoTagRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12$\n\ttelemetry\x18\x02 \x01(\x0b\x32\x11.uuaspb.Telemetry\"6\n\x0eGeoTagResponse\x12$\n\x06result\x18\x01 \x01(\x0e\x32\x14.uuaspb.ResultStatus\"#\n\x0fUnGeoTagRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"^\n\x10UnGeoTagResponse\x12$\n\x06result\x18\x01 \x01(\x0e\x32\x14.uuaspb.ResultStatus\x12$\n\ttelemetry\x18\x02 \x01(\x0b\x32\x11.uuaspb.Telemetry\"\xf3\x02\n\tTelemetry\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x16\n\x0e\x61ltitude_agl_m\x18\x03 \x01(\x01\x12\x16\n\x0e\x61ltitude_msl_m\x18\x04 \x01(\x01\x12\x13\n\x0bheading_deg\x18\x05 \x01(\x01\x12\x15\n\rvelocityx_m_s\x18\x06 \x01(\x01\x12\x15\n\rvelocityy_m_s\x18\x07 \x01(\x01\x12\x15\n\rvelocityz_m_s\x18\x08 \x01(\x01\x12\x10\n\x08roll_rad\x18\t \x01(\x01\x12\x11\n\tpitch_rad\x18\n \x01(\x01\x12\x0f\n\x07yaw_rad\x18\x0b \x01(\x01\x12\x17\n\x0frollspeed_rad_s\x18\x0c \x01(\x01\x12\x18\n\x10pitchspeed_rad_s\x18\r \x01(\x01\x12\x16\n\x0eyawspeed_rad_s\x18\x0e \x01(\x01\x12\x1c\n\x14timestamp_pixhawk_ms\x18\x0f \x01(\x04\x12\x18\n\x10timestamp_msg_ms\x18\x10 \x01(\x04*\x1f\n\x0cResultStatus\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x62\x06proto3'
)

_RESULTSTATUS = _descriptor.EnumDescriptor(
  name='ResultStatus',
  full_name='uuaspb.ResultStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=660,
  serialized_end=691,
)
_sym_db.RegisterEnumDescriptor(_RESULTSTATUS)

ResultStatus = enum_type_wrapper.EnumTypeWrapper(_RESULTSTATUS)
OK = 0
ERR = 1



_GEOTAGREQUEST = _descriptor.Descriptor(
  name='GeoTagRequest',
  full_name='uuaspb.GeoTagRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='uuaspb.GeoTagRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='uuaspb.GeoTagRequest.telemetry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=95,
)


_GEOTAGRESPONSE = _descriptor.Descriptor(
  name='GeoTagResponse',
  full_name='uuaspb.GeoTagResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='uuaspb.GeoTagResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=151,
)


_UNGEOTAGREQUEST = _descriptor.Descriptor(
  name='UnGeoTagRequest',
  full_name='uuaspb.UnGeoTagRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='uuaspb.UnGeoTagRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=188,
)


_UNGEOTAGRESPONSE = _descriptor.Descriptor(
  name='UnGeoTagResponse',
  full_name='uuaspb.UnGeoTagResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='uuaspb.UnGeoTagResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='uuaspb.UnGeoTagResponse.telemetry', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=284,
)


_TELEMETRY = _descriptor.Descriptor(
  name='Telemetry',
  full_name='uuaspb.Telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='uuaspb.Telemetry.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='uuaspb.Telemetry.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_agl_m', full_name='uuaspb.Telemetry.altitude_agl_m', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_msl_m', full_name='uuaspb.Telemetry.altitude_msl_m', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading_deg', full_name='uuaspb.Telemetry.heading_deg', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocityx_m_s', full_name='uuaspb.Telemetry.velocityx_m_s', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocityy_m_s', full_name='uuaspb.Telemetry.velocityy_m_s', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocityz_m_s', full_name='uuaspb.Telemetry.velocityz_m_s', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roll_rad', full_name='uuaspb.Telemetry.roll_rad', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pitch_rad', full_name='uuaspb.Telemetry.pitch_rad', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw_rad', full_name='uuaspb.Telemetry.yaw_rad', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollspeed_rad_s', full_name='uuaspb.Telemetry.rollspeed_rad_s', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pitchspeed_rad_s', full_name='uuaspb.Telemetry.pitchspeed_rad_s', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yawspeed_rad_s', full_name='uuaspb.Telemetry.yawspeed_rad_s', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_pixhawk_ms', full_name='uuaspb.Telemetry.timestamp_pixhawk_ms', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_msg_ms', full_name='uuaspb.Telemetry.timestamp_msg_ms', index=15,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=658,
)

_GEOTAGREQUEST.fields_by_name['telemetry'].message_type = _TELEMETRY
_GEOTAGRESPONSE.fields_by_name['result'].enum_type = _RESULTSTATUS
_UNGEOTAGRESPONSE.fields_by_name['result'].enum_type = _RESULTSTATUS
_UNGEOTAGRESPONSE.fields_by_name['telemetry'].message_type = _TELEMETRY
DESCRIPTOR.message_types_by_name['GeoTagRequest'] = _GEOTAGREQUEST
DESCRIPTOR.message_types_by_name['GeoTagResponse'] = _GEOTAGRESPONSE
DESCRIPTOR.message_types_by_name['UnGeoTagRequest'] = _UNGEOTAGREQUEST
DESCRIPTOR.message_types_by_name['UnGeoTagResponse'] = _UNGEOTAGRESPONSE
DESCRIPTOR.message_types_by_name['Telemetry'] = _TELEMETRY
DESCRIPTOR.enum_types_by_name['ResultStatus'] = _RESULTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoTagRequest = _reflection.GeneratedProtocolMessageType('GeoTagRequest', (_message.Message,), {
  'DESCRIPTOR' : _GEOTAGREQUEST,
  '__module__' : 'uuaspb_pb2'
  # @@protoc_insertion_point(class_scope:uuaspb.GeoTagRequest)
  })
_sym_db.RegisterMessage(GeoTagRequest)

GeoTagResponse = _reflection.GeneratedProtocolMessageType('GeoTagResponse', (_message.Message,), {
  'DESCRIPTOR' : _GEOTAGRESPONSE,
  '__module__' : 'uuaspb_pb2'
  # @@protoc_insertion_point(class_scope:uuaspb.GeoTagResponse)
  })
_sym_db.RegisterMessage(GeoTagResponse)

UnGeoTagRequest = _reflection.GeneratedProtocolMessageType('UnGeoTagRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNGEOTAGREQUEST,
  '__module__' : 'uuaspb_pb2'
  # @@protoc_insertion_point(class_scope:uuaspb.UnGeoTagRequest)
  })
_sym_db.RegisterMessage(UnGeoTagRequest)

UnGeoTagResponse = _reflection.GeneratedProtocolMessageType('UnGeoTagResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNGEOTAGRESPONSE,
  '__module__' : 'uuaspb_pb2'
  # @@protoc_insertion_point(class_scope:uuaspb.UnGeoTagResponse)
  })
_sym_db.RegisterMessage(UnGeoTagResponse)

Telemetry = _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'uuaspb_pb2'
  # @@protoc_insertion_point(class_scope:uuaspb.Telemetry)
  })
_sym_db.RegisterMessage(Telemetry)


# @@protoc_insertion_point(module_scope)
