// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uuaspb.proto

#include "uuaspb.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_uuaspb_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Telemetry_uuaspb_2eproto;
namespace uuas {
class GeoTagRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GeoTagRequest> _instance;
} _GeoTagRequest_default_instance_;
class TelemetryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Telemetry> _instance;
} _Telemetry_default_instance_;
}  // namespace uuas
static void InitDefaultsscc_info_GeoTagRequest_uuaspb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::uuas::_GeoTagRequest_default_instance_;
    new (ptr) ::uuas::GeoTagRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::uuas::GeoTagRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GeoTagRequest_uuaspb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GeoTagRequest_uuaspb_2eproto}, {
      &scc_info_Telemetry_uuaspb_2eproto.base,}};

static void InitDefaultsscc_info_Telemetry_uuaspb_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::uuas::_Telemetry_default_instance_;
    new (ptr) ::uuas::Telemetry();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::uuas::Telemetry::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Telemetry_uuaspb_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Telemetry_uuaspb_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_uuaspb_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_uuaspb_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_uuaspb_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_uuaspb_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::uuas::GeoTagRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::uuas::GeoTagRequest, filename_),
  PROTOBUF_FIELD_OFFSET(::uuas::GeoTagRequest, telemetry_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, latitude_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, longitude_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, altitude_agl_meters_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, altitude_msl_meters_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, heading_degrees_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, velocity_x_cm_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, velocity_y_cm_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, velocity_z_cm_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, roll_rad_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, pitch_rad_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, yaw_rad_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, rollspeed_rad_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, pitchspeed_rad_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, yawspeed_rad_s_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, timestamp_telem_ms_),
  PROTOBUF_FIELD_OFFSET(::uuas::Telemetry, timestamp_msg_ms_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::uuas::GeoTagRequest)},
  { 7, -1, sizeof(::uuas::Telemetry)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::uuas::_GeoTagRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::uuas::_Telemetry_default_instance_),
};

const char descriptor_table_protodef_uuaspb_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014uuaspb.proto\022\004uuas\"E\n\rGeoTagRequest\022\020\n"
  "\010filename\030\001 \001(\t\022\"\n\ttelemetry\030\002 \001(\0132\017.uua"
  "s.Telemetry\"\205\003\n\tTelemetry\022\020\n\010latitude\030\001 "
  "\001(\022\022\021\n\tlongitude\030\002 \001(\022\022\033\n\023altitude_agl_m"
  "eters\030\003 \001(\r\022\033\n\023altitude_msl_meters\030\004 \001(\r"
  "\022\027\n\017heading_degrees\030\005 \001(\r\022\027\n\017velocity_x_"
  "cm_s\030\006 \001(\001\022\027\n\017velocity_y_cm_s\030\007 \001(\001\022\027\n\017v"
  "elocity_z_cm_s\030\010 \001(\001\022\020\n\010roll_rad\030\t \001(\001\022\021"
  "\n\tpitch_rad\030\n \001(\001\022\017\n\007yaw_rad\030\013 \001(\001\022\027\n\017ro"
  "llspeed_rad_s\030\014 \001(\001\022\030\n\020pitchspeed_rad_s\030"
  "\r \001(\001\022\026\n\016yawspeed_rad_s\030\016 \001(\001\022\032\n\022timesta"
  "mp_telem_ms\030\017 \001(\004\022\030\n\020timestamp_msg_ms\030\020 "
  "\001(\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_uuaspb_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_uuaspb_2eproto_sccs[2] = {
  &scc_info_GeoTagRequest_uuaspb_2eproto.base,
  &scc_info_Telemetry_uuaspb_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_uuaspb_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_uuaspb_2eproto = {
  false, false, descriptor_table_protodef_uuaspb_2eproto, "uuaspb.proto", 491,
  &descriptor_table_uuaspb_2eproto_once, descriptor_table_uuaspb_2eproto_sccs, descriptor_table_uuaspb_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_uuaspb_2eproto::offsets,
  file_level_metadata_uuaspb_2eproto, 2, file_level_enum_descriptors_uuaspb_2eproto, file_level_service_descriptors_uuaspb_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_uuaspb_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_uuaspb_2eproto)), true);
namespace uuas {

// ===================================================================

void GeoTagRequest::InitAsDefaultInstance() {
  ::uuas::_GeoTagRequest_default_instance_._instance.get_mutable()->telemetry_ = const_cast< ::uuas::Telemetry*>(
      ::uuas::Telemetry::internal_default_instance());
}
class GeoTagRequest::_Internal {
 public:
  static const ::uuas::Telemetry& telemetry(const GeoTagRequest* msg);
};

const ::uuas::Telemetry&
GeoTagRequest::_Internal::telemetry(const GeoTagRequest* msg) {
  return *msg->telemetry_;
}
GeoTagRequest::GeoTagRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:uuas.GeoTagRequest)
}
GeoTagRequest::GeoTagRequest(const GeoTagRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_filename().empty()) {
    filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_filename(),
      GetArena());
  }
  if (from._internal_has_telemetry()) {
    telemetry_ = new ::uuas::Telemetry(*from.telemetry_);
  } else {
    telemetry_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:uuas.GeoTagRequest)
}

void GeoTagRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GeoTagRequest_uuaspb_2eproto.base);
  filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  telemetry_ = nullptr;
}

GeoTagRequest::~GeoTagRequest() {
  // @@protoc_insertion_point(destructor:uuas.GeoTagRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GeoTagRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete telemetry_;
}

void GeoTagRequest::ArenaDtor(void* object) {
  GeoTagRequest* _this = reinterpret_cast< GeoTagRequest* >(object);
  (void)_this;
}
void GeoTagRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GeoTagRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GeoTagRequest& GeoTagRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GeoTagRequest_uuaspb_2eproto.base);
  return *internal_default_instance();
}


void GeoTagRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:uuas.GeoTagRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && telemetry_ != nullptr) {
    delete telemetry_;
  }
  telemetry_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GeoTagRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "uuas.GeoTagRequest.filename"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .uuas.Telemetry telemetry = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_telemetry(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GeoTagRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:uuas.GeoTagRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string filename = 1;
  if (this->filename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "uuas.GeoTagRequest.filename");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_filename(), target);
  }

  // .uuas.Telemetry telemetry = 2;
  if (this->has_telemetry()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::telemetry(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uuas.GeoTagRequest)
  return target;
}

size_t GeoTagRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uuas.GeoTagRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 1;
  if (this->filename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // .uuas.Telemetry telemetry = 2;
  if (this->has_telemetry()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *telemetry_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GeoTagRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uuas.GeoTagRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GeoTagRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GeoTagRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uuas.GeoTagRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uuas.GeoTagRequest)
    MergeFrom(*source);
  }
}

void GeoTagRequest::MergeFrom(const GeoTagRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uuas.GeoTagRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.filename().size() > 0) {
    _internal_set_filename(from._internal_filename());
  }
  if (from.has_telemetry()) {
    _internal_mutable_telemetry()->::uuas::Telemetry::MergeFrom(from._internal_telemetry());
  }
}

void GeoTagRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uuas.GeoTagRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GeoTagRequest::CopyFrom(const GeoTagRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uuas.GeoTagRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeoTagRequest::IsInitialized() const {
  return true;
}

void GeoTagRequest::InternalSwap(GeoTagRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  filename_.Swap(&other->filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(telemetry_, other->telemetry_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GeoTagRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Telemetry::InitAsDefaultInstance() {
}
class Telemetry::_Internal {
 public:
};

Telemetry::Telemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:uuas.Telemetry)
}
Telemetry::Telemetry(const Telemetry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&heading_degrees_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(heading_degrees_));
  // @@protoc_insertion_point(copy_constructor:uuas.Telemetry)
}

void Telemetry::SharedCtor() {
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_degrees_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(heading_degrees_));
}

Telemetry::~Telemetry() {
  // @@protoc_insertion_point(destructor:uuas.Telemetry)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Telemetry::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Telemetry::ArenaDtor(void* object) {
  Telemetry* _this = reinterpret_cast< Telemetry* >(object);
  (void)_this;
}
void Telemetry::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Telemetry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Telemetry& Telemetry::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Telemetry_uuaspb_2eproto.base);
  return *internal_default_instance();
}


void Telemetry::Clear() {
// @@protoc_insertion_point(message_clear_start:uuas.Telemetry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_degrees_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(heading_degrees_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Telemetry::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // sint64 latitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // sint64 longitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 altitude_agl_meters = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          altitude_agl_meters_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 altitude_msl_meters = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          altitude_msl_meters_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 heading_degrees = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          heading_degrees_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double velocity_x_cm_s = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          velocity_x_cm_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double velocity_y_cm_s = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          velocity_y_cm_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double velocity_z_cm_s = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          velocity_z_cm_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double roll_rad = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          roll_rad_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double pitch_rad = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          pitch_rad_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double yaw_rad = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          yaw_rad_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double rollspeed_rad_s = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 97)) {
          rollspeed_rad_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double pitchspeed_rad_s = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 105)) {
          pitchspeed_rad_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double yawspeed_rad_s = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 113)) {
          yawspeed_rad_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // uint64 timestamp_telem_ms = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          timestamp_telem_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 timestamp_msg_ms = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 128)) {
          timestamp_msg_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Telemetry::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:uuas.Telemetry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sint64 latitude = 1;
  if (this->latitude() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt64ToArray(1, this->_internal_latitude(), target);
  }

  // sint64 longitude = 2;
  if (this->longitude() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt64ToArray(2, this->_internal_longitude(), target);
  }

  // uint32 altitude_agl_meters = 3;
  if (this->altitude_agl_meters() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_altitude_agl_meters(), target);
  }

  // uint32 altitude_msl_meters = 4;
  if (this->altitude_msl_meters() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_altitude_msl_meters(), target);
  }

  // uint32 heading_degrees = 5;
  if (this->heading_degrees() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_heading_degrees(), target);
  }

  // double velocity_x_cm_s = 6;
  if (!(this->velocity_x_cm_s() <= 0 && this->velocity_x_cm_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(6, this->_internal_velocity_x_cm_s(), target);
  }

  // double velocity_y_cm_s = 7;
  if (!(this->velocity_y_cm_s() <= 0 && this->velocity_y_cm_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_velocity_y_cm_s(), target);
  }

  // double velocity_z_cm_s = 8;
  if (!(this->velocity_z_cm_s() <= 0 && this->velocity_z_cm_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_velocity_z_cm_s(), target);
  }

  // double roll_rad = 9;
  if (!(this->roll_rad() <= 0 && this->roll_rad() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->_internal_roll_rad(), target);
  }

  // double pitch_rad = 10;
  if (!(this->pitch_rad() <= 0 && this->pitch_rad() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_pitch_rad(), target);
  }

  // double yaw_rad = 11;
  if (!(this->yaw_rad() <= 0 && this->yaw_rad() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(11, this->_internal_yaw_rad(), target);
  }

  // double rollspeed_rad_s = 12;
  if (!(this->rollspeed_rad_s() <= 0 && this->rollspeed_rad_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(12, this->_internal_rollspeed_rad_s(), target);
  }

  // double pitchspeed_rad_s = 13;
  if (!(this->pitchspeed_rad_s() <= 0 && this->pitchspeed_rad_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(13, this->_internal_pitchspeed_rad_s(), target);
  }

  // double yawspeed_rad_s = 14;
  if (!(this->yawspeed_rad_s() <= 0 && this->yawspeed_rad_s() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(14, this->_internal_yawspeed_rad_s(), target);
  }

  // uint64 timestamp_telem_ms = 15;
  if (this->timestamp_telem_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(15, this->_internal_timestamp_telem_ms(), target);
  }

  // uint64 timestamp_msg_ms = 16;
  if (this->timestamp_msg_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(16, this->_internal_timestamp_msg_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:uuas.Telemetry)
  return target;
}

size_t Telemetry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:uuas.Telemetry)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // sint64 latitude = 1;
  if (this->latitude() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt64Size(
        this->_internal_latitude());
  }

  // sint64 longitude = 2;
  if (this->longitude() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt64Size(
        this->_internal_longitude());
  }

  // uint32 altitude_agl_meters = 3;
  if (this->altitude_agl_meters() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_altitude_agl_meters());
  }

  // uint32 altitude_msl_meters = 4;
  if (this->altitude_msl_meters() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_altitude_msl_meters());
  }

  // double velocity_x_cm_s = 6;
  if (!(this->velocity_x_cm_s() <= 0 && this->velocity_x_cm_s() >= 0)) {
    total_size += 1 + 8;
  }

  // double velocity_y_cm_s = 7;
  if (!(this->velocity_y_cm_s() <= 0 && this->velocity_y_cm_s() >= 0)) {
    total_size += 1 + 8;
  }

  // double velocity_z_cm_s = 8;
  if (!(this->velocity_z_cm_s() <= 0 && this->velocity_z_cm_s() >= 0)) {
    total_size += 1 + 8;
  }

  // double roll_rad = 9;
  if (!(this->roll_rad() <= 0 && this->roll_rad() >= 0)) {
    total_size += 1 + 8;
  }

  // double pitch_rad = 10;
  if (!(this->pitch_rad() <= 0 && this->pitch_rad() >= 0)) {
    total_size += 1 + 8;
  }

  // double yaw_rad = 11;
  if (!(this->yaw_rad() <= 0 && this->yaw_rad() >= 0)) {
    total_size += 1 + 8;
  }

  // double rollspeed_rad_s = 12;
  if (!(this->rollspeed_rad_s() <= 0 && this->rollspeed_rad_s() >= 0)) {
    total_size += 1 + 8;
  }

  // double pitchspeed_rad_s = 13;
  if (!(this->pitchspeed_rad_s() <= 0 && this->pitchspeed_rad_s() >= 0)) {
    total_size += 1 + 8;
  }

  // double yawspeed_rad_s = 14;
  if (!(this->yawspeed_rad_s() <= 0 && this->yawspeed_rad_s() >= 0)) {
    total_size += 1 + 8;
  }

  // uint64 timestamp_telem_ms = 15;
  if (this->timestamp_telem_ms() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timestamp_telem_ms());
  }

  // uint64 timestamp_msg_ms = 16;
  if (this->timestamp_msg_ms() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timestamp_msg_ms());
  }

  // uint32 heading_degrees = 5;
  if (this->heading_degrees() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_heading_degrees());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Telemetry::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:uuas.Telemetry)
  GOOGLE_DCHECK_NE(&from, this);
  const Telemetry* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Telemetry>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:uuas.Telemetry)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:uuas.Telemetry)
    MergeFrom(*source);
  }
}

void Telemetry::MergeFrom(const Telemetry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:uuas.Telemetry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.latitude() != 0) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (from.longitude() != 0) {
    _internal_set_longitude(from._internal_longitude());
  }
  if (from.altitude_agl_meters() != 0) {
    _internal_set_altitude_agl_meters(from._internal_altitude_agl_meters());
  }
  if (from.altitude_msl_meters() != 0) {
    _internal_set_altitude_msl_meters(from._internal_altitude_msl_meters());
  }
  if (!(from.velocity_x_cm_s() <= 0 && from.velocity_x_cm_s() >= 0)) {
    _internal_set_velocity_x_cm_s(from._internal_velocity_x_cm_s());
  }
  if (!(from.velocity_y_cm_s() <= 0 && from.velocity_y_cm_s() >= 0)) {
    _internal_set_velocity_y_cm_s(from._internal_velocity_y_cm_s());
  }
  if (!(from.velocity_z_cm_s() <= 0 && from.velocity_z_cm_s() >= 0)) {
    _internal_set_velocity_z_cm_s(from._internal_velocity_z_cm_s());
  }
  if (!(from.roll_rad() <= 0 && from.roll_rad() >= 0)) {
    _internal_set_roll_rad(from._internal_roll_rad());
  }
  if (!(from.pitch_rad() <= 0 && from.pitch_rad() >= 0)) {
    _internal_set_pitch_rad(from._internal_pitch_rad());
  }
  if (!(from.yaw_rad() <= 0 && from.yaw_rad() >= 0)) {
    _internal_set_yaw_rad(from._internal_yaw_rad());
  }
  if (!(from.rollspeed_rad_s() <= 0 && from.rollspeed_rad_s() >= 0)) {
    _internal_set_rollspeed_rad_s(from._internal_rollspeed_rad_s());
  }
  if (!(from.pitchspeed_rad_s() <= 0 && from.pitchspeed_rad_s() >= 0)) {
    _internal_set_pitchspeed_rad_s(from._internal_pitchspeed_rad_s());
  }
  if (!(from.yawspeed_rad_s() <= 0 && from.yawspeed_rad_s() >= 0)) {
    _internal_set_yawspeed_rad_s(from._internal_yawspeed_rad_s());
  }
  if (from.timestamp_telem_ms() != 0) {
    _internal_set_timestamp_telem_ms(from._internal_timestamp_telem_ms());
  }
  if (from.timestamp_msg_ms() != 0) {
    _internal_set_timestamp_msg_ms(from._internal_timestamp_msg_ms());
  }
  if (from.heading_degrees() != 0) {
    _internal_set_heading_degrees(from._internal_heading_degrees());
  }
}

void Telemetry::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:uuas.Telemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Telemetry::CopyFrom(const Telemetry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:uuas.Telemetry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Telemetry::IsInitialized() const {
  return true;
}

void Telemetry::InternalSwap(Telemetry* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Telemetry, heading_degrees_)
      + sizeof(Telemetry::heading_degrees_)
      - PROTOBUF_FIELD_OFFSET(Telemetry, latitude_)>(
          reinterpret_cast<char*>(&latitude_),
          reinterpret_cast<char*>(&other->latitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Telemetry::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace uuas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::uuas::GeoTagRequest* Arena::CreateMaybeMessage< ::uuas::GeoTagRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::uuas::GeoTagRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::uuas::Telemetry* Arena::CreateMaybeMessage< ::uuas::Telemetry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::uuas::Telemetry >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
